from __future__ import annotations

import re
from pathlib import Path


BASELINE = Path("migrations/versions/20260608_0001_postgresql_baseline.py")


def _baseline_text() -> str:
    return BASELINE.read_text(encoding="utf-8")


def test_postgresql_baseline_uses_namespaces_for_storage_domains() -> None:
    text = _baseline_text()

    assert "CREATE SCHEMA IF NOT EXISTS wolf" in text
    assert "CREATE SCHEMA IF NOT EXISTS registry" in text
    assert "CREATE SCHEMA IF NOT EXISTS evolution" in text
    assert "CREATE TABLE registry.rejected_proposals" in text
    assert "CREATE TABLE evolution.rejected_proposals" in text
    assert "CREATE TABLE rejected_proposals" not in text


def test_postgresql_baseline_covers_current_storage_tables() -> None:
    text = _baseline_text()
    expected_tables = {
        "wolf.games",
        "wolf.players",
        "wolf.decisions",
        "wolf.game_events",
        "wolf.leaderboard",
        "wolf.evaluations",
        "wolf.decision_reviews",
        "wolf.counterfactuals",
        "wolf.reports",
        "wolf.llm_judgments",
        "wolf.seed_sets",
        "wolf.evaluation_batches",
        "wolf.benchmark_leaderboard",
        "registry.role_versions",
        "registry.role_current_baseline",
        "registry.role_baseline_history",
        "registry.skill_files",
        "registry.rejected_proposals",
        "evolution.evolution_runs",
        "evolution.skill_proposals",
        "evolution.experience_candidates",
        "evolution.patterns",
        "evolution.rejected_proposals",
        "evolution.situational_records",
        "evolution.decision_outcomes",
        "evolution.evolution_rounds",
        "evolution.candidate_packages",
        "evolution.promotion_decisions",
        "evolution.ab_comparison_groups",
    }

    for table in expected_tables:
        assert f"CREATE TABLE {table}" in text


def test_postgresql_baseline_preserves_high_risk_constraints() -> None:
    text = _baseline_text()

    assert "CONSTRAINT pk_role_versions PRIMARY KEY (id, role)" in text
    assert "CONSTRAINT pk_experience_candidates PRIMARY KEY (game_id, candidate_id)" in text
    assert "CONSTRAINT uq_players_game_seat UNIQUE (game_id, seat)" in text
    assert "CONSTRAINT uq_leaderboard_role_version UNIQUE (role, version_id)" in text
    assert "CONSTRAINT uq_reports_game UNIQUE (game_id)" in text
    assert "CONSTRAINT uq_skill_files_version_path UNIQUE (version_id, file_path)" in text


def test_postgresql_baseline_uses_pg_native_type_mappings() -> None:
    text = _baseline_text().lower()

    assert "generated by default as identity primary key" in text
    assert "timestamptz not null" in text
    assert "boolean default false" in text
    assert "boolean default true" in text
    assert "double precision default 0.0" in text
    assert "rowid" not in text
    assert "autoincrement" not in text
    assert "pragma" not in text


def test_postgresql_baseline_jsonb_policy_is_explicit_and_conservative() -> None:
    text = _baseline_text()

    for pattern in (
        r"config jsonb",
        r"public_events jsonb",
        r"final_state jsonb",
        r"payload jsonb",
        r"scores jsonb",
        r"input_refs jsonb",
        r"raw_json jsonb",
        r"seeds_json jsonb NOT NULL",
        r"by_role_category_scores jsonb",
        r"proposal_json jsonb NOT NULL",
        r"proposals_json jsonb NOT NULL",
    ):
        assert re.search(pattern, text), pattern

    for pattern in (
        r"role_version_config text",
        r"summary text",
        r"skills text NOT NULL",
        r"content text NOT NULL",
        r"ab_summary text",
        r"scenario text",
        r"conditions text",
        r"recommendation text",
        r"errors text",
    ):
        assert re.search(pattern, text), pattern


def test_alembic_scaffold_is_configured_for_postgresql_baseline() -> None:
    env_text = Path("migrations/env.py").read_text(encoding="utf-8")
    ini_text = Path("alembic.ini").read_text(encoding="utf-8")

    assert "include_schemas=True" in env_text
    assert "POSTGRES_DATABASE_URL" in env_text
    assert "DATABASE_URL" in env_text
    assert "script_location = migrations" in ini_text
    assert "postgresql+psycopg://" in ini_text
