from __future__ import annotations

import re
from pathlib import Path


BASELINE = Path("migrations/versions/20260608_0001_postgresql_baseline.py")
BENCHMARK_SAVED_VIEWS = Path("migrations/versions/20260610_0002_benchmark_saved_views.py")
UI_MODEL_PROFILES = Path("migrations/versions/20260611_0005_ui_model_profiles.py")
UI_RUNTIME_SETTINGS = Path("migrations/versions/20260611_0006_ui_runtime_settings.py")
UI_SETTINGS_AUDIT_LOG = Path("migrations/versions/20260611_0007_ui_settings_audit_log.py")


def _baseline_text() -> str:
    return BASELINE.read_text(encoding="utf-8")


def _benchmark_saved_views_text() -> str:
    return BENCHMARK_SAVED_VIEWS.read_text(encoding="utf-8")


def _ui_model_profiles_text() -> str:
    return UI_MODEL_PROFILES.read_text(encoding="utf-8")


def _ui_runtime_settings_text() -> str:
    return UI_RUNTIME_SETTINGS.read_text(encoding="utf-8")


def _ui_settings_audit_log_text() -> str:
    return UI_SETTINGS_AUDIT_LOG.read_text(encoding="utf-8")


def test_postgresql_baseline_uses_namespaces_for_storage_domains() -> None:
    text = _baseline_text()

    assert "CREATE SCHEMA IF NOT EXISTS wolf" in text
    assert "CREATE SCHEMA IF NOT EXISTS registry" in text
    assert "CREATE SCHEMA IF NOT EXISTS evolution" in text
    assert "CREATE TABLE registry.rejected_proposals" in text
    assert "CREATE TABLE evolution.rejected_proposals" in text
    assert "CREATE TABLE rejected_proposals" not in text


def test_postgresql_baseline_covers_current_storage_tables() -> None:
    text = _baseline_text()
    expected_tables = {
        "wolf.games",
        "wolf.players",
        "wolf.decisions",
        "wolf.game_events",
        "wolf.leaderboard",
        "wolf.evaluations",
        "wolf.decision_reviews",
        "wolf.counterfactuals",
        "wolf.reports",
        "wolf.llm_judgments",
        "wolf.seed_sets",
        "wolf.evaluation_batches",
        "wolf.benchmark_leaderboard",
        "wolf.benchmark_leaderboard_snapshots",
        "registry.role_versions",
        "registry.role_current_baseline",
        "registry.role_baseline_history",
        "registry.skill_files",
        "registry.rejected_proposals",
        "evolution.evolution_runs",
        "evolution.trust_bundles",
        "evolution.skill_proposals",
        "evolution.experience_candidates",
        "evolution.patterns",
        "evolution.rejected_proposals",
        "evolution.situational_records",
        "evolution.decision_outcomes",
        "evolution.evolution_rounds",
        "evolution.candidate_packages",
        "evolution.promotion_decisions",
        "evolution.ab_comparison_groups",
    }

    for table in expected_tables:
        assert f"CREATE TABLE {table}" in text


def test_postgresql_baseline_preserves_high_risk_constraints() -> None:
    text = _baseline_text()

    assert "CONSTRAINT pk_role_versions PRIMARY KEY (id, role)" in text
    assert "CONSTRAINT pk_experience_candidates PRIMARY KEY (game_id, candidate_id)" in text
    assert "CONSTRAINT uq_players_game_seat UNIQUE (game_id, seat)" in text
    assert "CONSTRAINT uq_leaderboard_role_version UNIQUE (role, version_id)" in text
    assert "CONSTRAINT uq_reports_game UNIQUE (game_id)" in text
    assert "CONSTRAINT uq_skill_files_version_path UNIQUE (version_id, file_path)" in text
    assert "run_id text NOT NULL UNIQUE" in text
    assert "bundle_hash text NOT NULL" in text
    assert "CREATE INDEX idx_trust_bundles_run ON evolution.trust_bundles(run_id)" in text
    assert "CREATE INDEX idx_trust_bundles_role ON evolution.trust_bundles(role)" in text


def test_postgresql_baseline_uses_pg_native_type_mappings() -> None:
    text = _baseline_text().lower()

    assert "generated by default as identity primary key" in text
    assert "timestamptz not null" in text
    assert "boolean default false" in text
    assert "boolean default true" in text
    assert "double precision default 0.0" in text
    assert "rowid" not in text
    assert "autoincrement" not in text
    assert "pragma" not in text


def test_postgresql_baseline_jsonb_policy_is_explicit_and_conservative() -> None:
    text = _baseline_text()

    for pattern in (
        r"config jsonb",
        r"public_events jsonb",
        r"final_state jsonb",
        r"payload jsonb",
        r"scores jsonb",
        r"input_refs jsonb",
        r"raw_json jsonb",
        r"seeds_json jsonb NOT NULL",
        r"by_role_category_scores jsonb",
        r"source_filter jsonb",
        r"view_config jsonb",
        r"rows_json jsonb NOT NULL",
        r"summary_json jsonb NOT NULL",
        r"proposal_json jsonb NOT NULL",
        r"proposals_json jsonb NOT NULL",
        r"bundle_json jsonb NOT NULL",
    ):
        assert re.search(pattern, text), pattern

    for pattern in (
        r"role_version_config text",
        r"summary text",
        r"skills text NOT NULL",
        r"content text NOT NULL",
        r"ab_summary text",
        r"scenario text",
        r"conditions text",
        r"recommendation text",
        r"errors text",
    ):
        assert re.search(pattern, text), pattern


def test_alembic_scaffold_is_configured_for_postgresql_baseline() -> None:
    env_text = Path("migrations/env.py").read_text(encoding="utf-8")
    ini_text = Path("alembic.ini").read_text(encoding="utf-8")

    assert "include_schemas=True" in env_text
    assert "POSTGRES_DATABASE_URL" in env_text
    assert "DATABASE_URL" in env_text
    assert "script_location = migrations" in ini_text
    assert "postgresql+psycopg://" in ini_text


def test_benchmark_saved_views_migration_owns_saved_view_schema() -> None:
    baseline_text = _baseline_text()
    migration_text = _benchmark_saved_views_text()
    compact_migration = re.sub(r"\s+", " ", migration_text)

    assert "CREATE TABLE wolf.benchmark_saved_views" not in baseline_text
    assert 'down_revision = "20260608_0001"' in migration_text
    assert "CREATE TABLE IF NOT EXISTS wolf.benchmark_saved_views" in compact_migration
    assert "view_key text PRIMARY KEY" in migration_text
    assert "view_config jsonb NOT NULL" in migration_text
    assert "CREATE INDEX IF NOT EXISTS idx_bench_view_scope_eval " in migration_text
    assert "ON wolf.benchmark_saved_views(scope, evaluation_set_id)" in migration_text
    assert "CREATE INDEX IF NOT EXISTS idx_bench_view_benchmark " in migration_text
    assert "ON wolf.benchmark_saved_views(benchmark_id)" in migration_text


def test_ui_model_profiles_migration_owns_encrypted_settings_schema() -> None:
    migration_text = _ui_model_profiles_text()
    compact_migration = re.sub(r"\s+", " ", migration_text)

    assert 'down_revision = "20260610_0004"' in migration_text
    assert "CREATE TABLE IF NOT EXISTS wolf.ui_model_profiles" in compact_migration
    assert "profile_id text PRIMARY KEY" in migration_text
    assert "api_key_ciphertext text" in migration_text
    assert "api_key_kid text" in migration_text
    assert "api_key_masked text" in migration_text
    assert "default_scopes jsonb NOT NULL" in migration_text
    assert "capabilities jsonb NOT NULL" in migration_text
    assert "enabled boolean NOT NULL DEFAULT true" in migration_text
    assert "model-profile-secrets.json" not in migration_text
    assert "api_key text" not in migration_text


def test_ui_runtime_settings_migration_owns_non_secret_variable_schema() -> None:
    migration_text = _ui_runtime_settings_text()
    compact_migration = re.sub(r"\s+", " ", migration_text)

    assert 'down_revision = "20260611_0005"' in migration_text
    assert "CREATE TABLE IF NOT EXISTS wolf.ui_runtime_settings" in compact_migration
    assert "setting_key text PRIMARY KEY" in migration_text
    assert "value_json jsonb NOT NULL" in migration_text
    assert "updated_at timestamptz NOT NULL" in migration_text
    assert "updated_by text" in migration_text
    assert "secret" not in migration_text.lower()


def test_ui_settings_audit_log_migration_owns_settings_governance_schema() -> None:
    migration_text = _ui_settings_audit_log_text()
    compact_migration = re.sub(r"\s+", " ", migration_text)

    assert 'down_revision = "20260611_0006"' in migration_text
    assert "CREATE TABLE IF NOT EXISTS wolf.ui_settings_audit_log" in compact_migration
    assert "audit_id text PRIMARY KEY" in migration_text
    assert "action text NOT NULL" in migration_text
    assert "entity_kind text NOT NULL" in migration_text
    assert "entity_id text NOT NULL" in migration_text
    assert "details jsonb NOT NULL" in migration_text
    assert "idx_ui_settings_audit_created" in migration_text
    assert "api_key text" not in migration_text
