import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

function readSource(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8')
}

test('LabWorkbenchShell exposes shared Lab boundary, tabs, action, and main pane semantics', () => {
  const shell = readSource('../src/components/lab/LabWorkbenchShell.vue')

  assert.match(shell, /workbenchKey:\s*\{\s*type:\s*String,\s*default:\s*'lab'\s*\}/)
  assert.match(shell, /tabs:\s*\{\s*type:\s*Array,\s*default:\s*\(\) => \[\]\s*\}/)
  assert.match(shell, /activeTab:\s*\{\s*type:\s*String,\s*default:\s*''\s*\}/)
  assert.match(shell, /contextLabel:\s*\{\s*type:\s*String,\s*default:\s*'Lab context panel'\s*\}/)
  assert.match(shell, /const emit = defineEmits\(\['update:activeTab', 'action'\]\)/)
  assert.match(shell, /const hasContext = computed\(\(\) => Boolean\(slots\.context\)\)/)
  assert.match(shell, /function selectTab\(tab\)[\s\S]*emit\('update:activeTab', tab\.key\)/)

  assert.match(shell, /class="lab-workbench-action-bar"[\s\S]*:aria-label="`\$\{title\} 操作区`"/)
  assert.match(shell, /class="lab-workbench-boundary-bar"[\s\S]*:aria-label="boundaryLabel"/)
  assert.match(shell, /class="lab-workbench-tabs"[\s\S]*data-lab-tabs/)
  assert.match(shell, /:aria-current="activeTab === tab\.key \? 'page' : undefined"/)
  assert.match(shell, /class="lab-workbench-main-pane"[\s\S]*:aria-label="mainLabel \|\| `\$\{activeTabLabel\} 主面板`"/)
  assert.match(shell, /<aside v-if="hasContext" class="lab-workbench-context" :aria-label="contextLabel">[\s\S]*<slot name="context" \/>[\s\S]*<\/aside>/)
  assert.match(shell, /class="lab-workbench-action-area"[\s\S]*class="lab-workbench-primary-action"[\s\S]*@click="emit\('action'\)"/)
})

test('LabWorkbenchShell keeps dense Lab layout mobile-safe', () => {
  const shell = readSource('../src/components/lab/LabWorkbenchShell.vue')

  assert.match(shell, /\.lab-workbench-bridge\s*\{[\s\S]*display:\s*contents/)
  assert.match(shell, /\.lab-workbench-shell\s*\{[\s\S]*grid-template-columns:\s*var\(--lab-rail-width,\s*316px\) minmax\(0, 1fr\)[\s\S]*overflow:\s*hidden/)
  assert.match(shell, /\.lab-workbench-shell--has-context\s*\{[\s\S]*grid-template-columns:[\s\S]*var\(--lab-rail-width,\s*316px\)[\s\S]*minmax\(0, 1fr\)[\s\S]*var\(--lab-context-width,\s*320px\)/)
  assert.match(shell, /\.lab-workbench-context\s*\{[\s\S]*overflow:\s*hidden/)
  assert.match(shell, /\.lab-workbench-main\s*\{[\s\S]*grid-template-rows:\s*auto auto auto auto minmax\(0, 1fr\)[\s\S]*overflow:\s*hidden/)
  assert.match(shell, /\.lab-workbench-tabs\s*\{[\s\S]*overflow-x:\s*auto/)
  assert.match(shell, /\.lab-workbench-tab span\s*\{[\s\S]*text-overflow:\s*ellipsis[\s\S]*white-space:\s*nowrap/)
  assert.match(shell, /\.lab-workbench-main-pane\s*\{[\s\S]*min-width:\s*0[\s\S]*min-height:\s*0[\s\S]*overflow:\s*hidden/)
  assert.match(shell, /@media \(max-width: 960px\)[\s\S]*\.lab-workbench-shell\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\)[\s\S]*overflow-x:\s*hidden/)
  assert.match(shell, /@media \(max-width: 640px\)[\s\S]*\.lab-workbench-tabs\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fit, minmax\(58px, 1fr\)\)/)
})

test('BenchmarkPage is wired to the shared Lab shell without changing benchmark business panels', () => {
  const benchmark = readSource('../src/pages/BenchmarkPage.vue')

  assert.match(benchmark, /import LabWorkbenchShell from '\.\.\/components\/lab\/LabWorkbenchShell\.vue'/)
  assert.match(benchmark, /const labHeaderMeta = computed\(\(\) => \[[\s\S]*key: 'mode'[\s\S]*key: 'suite'[\s\S]*key: 'budget'/)
  assert.match(benchmark, /<LabWorkbenchShell[\s\S]*v-model:active-tab="activeView"[\s\S]*workbench-key="benchmark"[\s\S]*:tabs="navTabs"[\s\S]*:meta="labHeaderMeta"[\s\S]*@action="refresh"/)
  assert.match(benchmark, /<template #rail>[\s\S]*<BenchmarkSuiteRail :benchmark="benchmark" \/>[\s\S]*<\/template>/)
  assert.match(benchmark, /<template #boundary>[\s\S]*<BenchmarkBoundaryBar :benchmark="benchmark" \/>[\s\S]*selectedBenchmarkUsingLegacyRuns/)
  assert.match(benchmark, /<template #notice>[\s\S]*<ApiErrorPanel[\s\S]*@retry="refresh"[\s\S]*<\/template>/)
  assert.match(benchmark, /<template #context>[\s\S]*class="bench-context-panel"[\s\S]*当前套件[\s\S]*运行上下文[\s\S]*诊断概览[\s\S]*审计边界[\s\S]*发布材料[\s\S]*<\/template>/)
  assert.match(benchmark, /<BenchmarkComparisonView[\s\S]*activeView === 'leaderboards'/)
  assert.match(benchmark, /<BenchmarkBatchRunsTable[\s\S]*activeView === 'runs'/)
  assert.match(benchmark, /<BenchmarkDiagnosticsExplorer[\s\S]*activeView === 'diagnostics'/)
  assert.match(benchmark, /<BenchmarkSnapshotReleasePanel :benchmark="benchmark" \/>[\s\S]*<BenchmarkRunReportPanel :benchmark="benchmark" \/>/)
})

test('Benchmark launch and target panels keep Chinese-first benchmark terminology', () => {
  const benchmark = readSource('../src/pages/BenchmarkPage.vue')
  const boundary = readSource('../src/components/benchmark/BenchmarkBoundaryBar.vue')
  const config = readSource('../src/components/benchmark/BenchmarkConfigPanel.vue')
  const target = readSource('../src/components/benchmark/BenchmarkTargetSelector.vue')

  assert.match(config, /props\.benchmark\.selectedBenchmarkId\.value \? '正式套件' : '临时评测'/)
  assert.match(config, /`\$\{count\} 个种子`/)
  assert.match(config, /<small>种子集<\/small>/)
  assert.match(config, /<small>预计调用单位<\/small>/)
  assert.match(config, /<small>预计成本<\/small>/)
  assert.match(config, /<small>预计 Token<\/small>|<small>预计 token<\/small>/)
  assert.match(config, /<small>预检模式<\/small>/)
  assert.doesNotMatch(config, /正式 suite|个 seed|固定 seed|<small>Seed Set<\/small>|<small>Dry-run<\/small>|<small>Dry Run<\/small>/)

  assert.match(target, /模型评测写入 scope=model 榜单/)
  assert.match(target, /角色版本评测写入 scope=role_version/)
  assert.match(target, /Config Hash/)
  assert.doesNotMatch(target, /model\/runtime config|启动 payload|roles 或 target_versions/)

  assert.match(benchmark, /const currentScopeLabel = computed/)
  assert.match(benchmark, /label: '范围', value: currentScopeLabel\.value/)
  assert.match(benchmark, /label: '评测集'/)
  assert.match(benchmark, /label: '种子集'/)
  assert.match(benchmark, /quick 快速套件或临时评测/)
  assert.match(benchmark, /label: '并发策略'/)
  assert.match(benchmark, /批次 \$\{formatNumber\(roleConcurrency\)\}/)
  assert.match(benchmark, /对局 \$\{formatNumber\(gameConcurrency\)\}/)
  assert.match(benchmark, /Judge \$\{formatNumber\(judgeConcurrency\)\}/)
  assert.match(benchmark, /预计调用单位/)
  assert.match(benchmark, /label: '预计成本'/)
  assert.match(benchmark, /label: '预计 Token'|label: '预计 token'/)
  assert.match(benchmark, /label: '预计耗时'/)
  assert.match(benchmark, /label: '并发策略'/)
  assert.match(benchmark, /label: '预检模式'/)
  assert.match(benchmark, /超预算原因/)
  assert.match(benchmark, /预算与停止线提示/)
  assert.match(benchmark, /仅预估不启动|只做预算预检/)
  assert.doesNotMatch(benchmark, /label: 'Scope'|label: 'Evaluation Set'|label: 'Seed Set'|label: 'Dry Run'|<dt>Evaluation Set<\/dt>|<dt>Seed Set<\/dt>|个 Judge 并发进程|个 Judge 并发任务|预计单位/)

  assert.match(boundary, /props\.benchmark\.benchmarkPlanBudgetExceeded\.value\) return '预算超限'/)
  assert.doesNotMatch(boundary, /budget\.value\?\.exceeded\) return '预算超限'/)
})

test('EvolutionPage has a low-risk LabWorkbenchShell bridge around the existing evolution shell', () => {
  const evolution = readSource('../src/pages/EvolutionPage.vue')

  assert.match(evolution, /import LabWorkbenchShell from '\.\.\/components\/lab\/LabWorkbenchShell\.vue'/)
  assert.match(evolution, /<LabWorkbenchShell[\s\S]*v-model:active-tab="activeTab"[\s\S]*bridge[\s\S]*class="evo-lab-workbench-bridge"[\s\S]*workbench-key="evolution"[\s\S]*:tabs="navTabs"/)
  assert.match(evolution, /<LabWorkbenchShell[\s\S]*<EvolutionWorkbenchShell[\s\S]*v-model:active-tab="activeTab"[\s\S]*@select-role="evo\.selectRole"[\s\S]*<\/EvolutionWorkbenchShell>[\s\S]*<\/LabWorkbenchShell>/)
  assert.match(evolution, /<EvolutionProposalReviewPanel v-if="activeTab === 'review'" :evo="evo" \/>/)
})

test('Lab shell and EvolutionPage keep the warm logbook palette bridge', () => {
  const shell = readSource('../src/components/lab/LabWorkbenchShell.vue')
  const evolution = readSource('../src/pages/EvolutionPage.vue')
  const diff = readSource('../src/components/evolution/EvolutionDiffViewer.vue')
  const leaderboard = readSource('../src/components/evolution/EvolutionLeaderboardPanel.vue')
  const versions = readSource('../src/components/evolution/EvolutionVersionsPanel.vue')
  const reject = readSource('../src/components/evolution/RejectDialog.vue')
  const trust = readSource('../src/components/evolution/TrustBundleDrawer.vue')
  const combined = [evolution, diff, leaderboard, versions, reject, trust].join('\n')

  assert.match(shell, /--lab-bg:\s*var\(--bench-bg,\s*var\(--evo-bg,\s*var\(--logbook-bg,\s*#f2dfae\)\)\)/)
  assert.match(shell, /--lab-panel:\s*var\(--bench-panel,\s*var\(--evo-surface,\s*var\(--logbook-panel,\s*rgba\(255, 252, 245, 0\.82\)\)\)\)/)
  assert.match(shell, /--lab-border:\s*var\(--bench-border,\s*var\(--evo-border,\s*var\(--logbook-border,\s*rgba\(93, 48, 17, 0\.18\)\)\)\)/)
  assert.match(shell, /--lab-active-bg:\s*var\(--bench-active-bg,\s*var\(--evo-active-bg,\s*var\(--logbook-active-bg,\s*rgba\(139, 94, 52, 0\.1\)\)\)\)/)

  assert.match(evolution, /--logbook-bg:\s*#f2dfae/)
  assert.match(evolution, /--logbook-bg-texture:[\s\S]*repeating-linear-gradient\(90deg,\s*rgba\(118, 71, 27, 0\.024\)[\s\S]*var\(--logbook-bg\)/)
  assert.match(evolution, /--evo-bg:\s*var\(--logbook-bg\)/)
  assert.match(evolution, /--evo-bg-texture:\s*var\(--logbook-bg-texture\)/)
  assert.match(evolution, /--evo-surface:\s*var\(--logbook-surface\)/)
  assert.match(evolution, /--evo-card-bg:\s*var\(--logbook-surface\)/)
  assert.match(evolution, /--evo-input-bg:\s*var\(--logbook-input-bg\)/)
  assert.match(evolution, /--evo-hover:\s*var\(--logbook-hover\)/)
  assert.match(evolution, /--evo-active-bg:\s*var\(--logbook-active-bg\)/)
  assert.match(evolution, /--evo-diff-added-marker:\s*#f0d690/)
  assert.match(evolution, /--evo-diff-removed-marker:\s*#f2a08b/)
  assert.match(evolution, /\.evo-diff-line-added \.evo-diff-line-marker\s*\{[\s\S]*color:\s*var\(--evo-diff-added-marker\)/)
  assert.match(evolution, /\.evo-diff-line-removed\s*\{[\s\S]*background:\s*var\(--evo-diff-removed-bg\)/)
  assert.match(evolution, /\.evo-shell\.parchment-logbook\s*\{[\s\S]*background:\s*var\(--evo-bg-texture\)/)

  assert.match(diff, /created:\s*'var\(--evo-success\)'/)
  assert.match(diff, /deleted:\s*'var\(--evo-danger\)'/)
  assert.match(leaderboard, /evo-leaderboard-bar/)
  assert.match(leaderboard, /is-baseline/)
  assert.match(versions, /PATTERN_STATUS_COLORS[\s\S]*active:\s*'var\(--evo-accent\)'/)
  assert.match(reject, /--logbook-bg-texture:[\s\S]*repeating-linear-gradient\(90deg,\s*rgba\(118, 71, 27, 0\.024\)[\s\S]*var\(--logbook-bg\)/)
  assert.match(reject, /--evo-bg-texture:\s*var\(--logbook-bg-texture\)/)
  assert.match(reject, /background:\s*var\(--evo-bg-texture\)/)
  assert.match(reject, /--evo-text:\s*var\(--logbook-text,\s*#3a2a18\)/)
  assert.match(trust, /--logbook-bg-texture:[\s\S]*repeating-linear-gradient\(90deg,\s*rgba\(118, 71, 27, 0\.024\)[\s\S]*var\(--logbook-bg\)/)
  assert.match(trust, /--evo-bg-texture:\s*var\(--logbook-bg-texture\)/)
  assert.match(trust, /background:\s*var\(--evo-bg-texture\)/)
  assert.match(trust, /--evo-text:\s*var\(--logbook-text,\s*#3a2a18\)/)
  assert.doesNotMatch(combined, /#4a9eff|#0f6b72|#2e7d32|#c62828|#f9a825|#f5a623/)
})
