"""Shared storage utilities -- compatibility re-exports from canonical interfaces."""

from __future__ import annotations

from storage.interfaces import (
    HasToDict,
    TimestampProvider,
    compute_hash,
    normalize_skill_path,
    normalize_skill_text,
    storage_timestamp,
    DecisionArchiveData,
    DecisionRecordData,
    EvolutionRunData,
    RoleHistoryData,
    RoleVersionData,
    SkillProposalData,
    SkillVersionConfigData,
)
from storage.shared.database import (
    ForUpdateConnection,
    InsertReturningIdConnection,
    SchemaIntrospectionConnection,
    SchemaMigrationConnection,
    SchemaVersionConnection,
    StorageConnection,
    StorageCursor,
    StorageRow,
    WriteTransactionConnection,
    add_column,
    begin_write,
    ensure_columns,
    execute_for_update,
    insert_returning_id,
    record_schema_version,
    table_columns,
    table_exists,
)
from storage.shared.sql import PlaceholderConversion, PlaceholderStyle, convert_qmark_placeholders

__all__ = [
    "PlaceholderConversion",
    "PlaceholderStyle",
    "ForUpdateConnection",
    "InsertReturningIdConnection",
    "SchemaIntrospectionConnection",
    "SchemaMigrationConnection",
    "SchemaVersionConnection",
    "StorageConnection",
    "StorageCursor",
    "StorageRow",
    "WriteTransactionConnection",
    "add_column",
    "begin_write",
    "convert_qmark_placeholders",
    "ensure_columns",
    "execute_for_update",
    "insert_returning_id",
    "record_schema_version",
    "table_columns",
    "table_exists",
    "HasToDict",
    "TimestampProvider",
    "compute_hash",
    "normalize_skill_path",
    "normalize_skill_text",
    "storage_timestamp",
    "DecisionArchiveData",
    "DecisionRecordData",
    "EvolutionRunData",
    "RoleHistoryData",
    "RoleVersionData",
    "SkillProposalData",
    "SkillVersionConfigData",
]
