"""PostgreSQL baseline schema.

PostgreSQL starts from this Alembic revision and uses schema namespaces to
preserve the current three-domain boundary without renaming tables.
"""

from __future__ import annotations

from alembic import op

revision = "20260608_0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_STATEMENTS = (
    "CREATE SCHEMA IF NOT EXISTS wolf",
    "CREATE SCHEMA IF NOT EXISTS registry",
    "CREATE SCHEMA IF NOT EXISTS evolution",
)


TABLE_STATEMENTS = (
    """
    CREATE TABLE wolf.games (
        id text PRIMARY KEY,
        seed integer NOT NULL,
        config jsonb,
        winner text,
        started_at timestamptz NOT NULL,
        finished_at timestamptz,
        total_rounds integer DEFAULT 0,
        public_events jsonb,
        final_state jsonb,
        run_type text DEFAULT 'ordinary_game',
        mode text DEFAULT 'dev',
        learning_eligible boolean DEFAULT false,
        leaderboard_scope text DEFAULT 'demo',
        promote_eligible boolean DEFAULT false,
        source_run_id text,
        comparison_group_id text,
        comparison_type text,
        model_id text,
        model_config_hash text,
        target_role text,
        target_version_id text,
        ruleset_version text DEFAULT 'werewolf_12p_v1',
        seed_set_id text,
        evaluation_set_id text,
        paired_seed boolean DEFAULT false,
        rankable boolean DEFAULT false
    )
    """,
    """
    CREATE TABLE wolf.players (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        game_id text NOT NULL REFERENCES wolf.games(id),
        seat integer NOT NULL,
        role text NOT NULL,
        team text NOT NULL,
        alive boolean DEFAULT true,
        killed_day integer,
        killed_cause text,
        role_version_id text,
        skill_package_hash text,
        model_id text,
        model_config_hash text,
        role_sample_status text DEFAULT 'valid',
        role_sample_invalid_reason text,
        CONSTRAINT uq_players_game_seat UNIQUE (game_id, seat)
    )
    """,
    """
    CREATE TABLE wolf.decisions (
        id text PRIMARY KEY,
        game_id text NOT NULL,
        player_id integer,
        seat integer NOT NULL,
        role text NOT NULL,
        day integer NOT NULL,
        phase text NOT NULL,
        action_type text NOT NULL,
        candidates text,
        observation_summary text,
        memory_context text,
        selected_skills text,
        prompt_messages text,
        raw_output text,
        parsed_decision text,
        final_response text,
        selected_target integer,
        selected_choice text,
        public_text text,
        private_reasoning text,
        confidence double precision,
        alternatives text,
        rejected_reasons text,
        memory_refs text,
        memory_summary text,
        source text,
        policy_adjustments text,
        errors text,
        version_id text,
        latency_ms double precision,
        prompt_tokens integer,
        completion_tokens integer,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE wolf.game_events (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        game_id text NOT NULL,
        idx integer NOT NULL,
        day integer NOT NULL,
        phase text NOT NULL,
        event_type text NOT NULL,
        message text,
        public boolean DEFAULT true,
        actor integer,
        target integer,
        payload jsonb,
        created_at timestamptz
    )
    """,
    """
    CREATE TABLE wolf.leaderboard (
        version_id text NOT NULL,
        role text NOT NULL,
        games_played integer DEFAULT 0,
        wins integer DEFAULT 0,
        losses integer DEFAULT 0,
        win_rate double precision DEFAULT 0.0,
        avg_survival_rounds double precision DEFAULT 0.0,
        target_side_win_rate double precision DEFAULT 0.0,
        win_rate_ci_low double precision DEFAULT 0.0,
        win_rate_ci_high double precision DEFAULT 0.0,
        scores jsonb,
        is_baseline boolean DEFAULT false,
        data_sufficient boolean DEFAULT false,
        avg_speech_score double precision DEFAULT 0.0,
        avg_vote_score double precision DEFAULT 0.0,
        avg_skill_score double precision DEFAULT 0.0,
        avg_information_score double precision DEFAULT 0.0,
        avg_cooperation_score double precision DEFAULT 0.0,
        updated_at timestamptz NOT NULL,
        CONSTRAINT uq_leaderboard_role_version UNIQUE (role, version_id)
    )
    """,
    """
    CREATE TABLE wolf.evaluations (
        id text PRIMARY KEY,
        game_id text NOT NULL REFERENCES wolf.games(id),
        player_seat integer,
        role text,
        speech_score double precision,
        vote_score double precision,
        skill_score double precision,
        logic_score double precision,
        team_score double precision,
        risk_penalty double precision DEFAULT 0.0,
        role_score double precision,
        score_completeness double precision DEFAULT 1.0,
        information_score double precision,
        cooperation_score double precision,
        overall_score double precision,
        role_sample_status text DEFAULT 'valid',
        role_sample_invalid_reason text,
        ruleset_version text DEFAULT 'werewolf_12p_v1',
        scoring_version text DEFAULT 'scoring_v1',
        evaluator_config_hash text DEFAULT 'rule_heuristic_v1',
        evaluation_status text DEFAULT 'completed',
        review_status text DEFAULT 'completed',
        report_status text DEFAULT 'completed',
        created_at timestamptz
    )
    """,
    """
    CREATE TABLE wolf.decision_reviews (
        id text PRIMARY KEY,
        game_id text NOT NULL REFERENCES wolf.games(id),
        decision_id text,
        player_seat integer,
        day integer,
        phase text,
        action_type text,
        quality text,
        reason text,
        alternative_action text,
        created_at timestamptz
    )
    """,
    """
    CREATE TABLE wolf.counterfactuals (
        id text PRIMARY KEY,
        game_id text NOT NULL REFERENCES wolf.games(id),
        decision_id text,
        what_if text,
        likely_outcome text,
        confidence double precision,
        created_at timestamptz
    )
    """,
    """
    CREATE TABLE wolf.reports (
        id text PRIMARY KEY,
        game_id text NOT NULL REFERENCES wolf.games(id),
        summary text,
        created_at timestamptz,
        CONSTRAINT uq_reports_game UNIQUE (game_id)
    )
    """,
    """
    CREATE TABLE wolf.llm_judgments (
        judgment_id text PRIMARY KEY,
        game_id text NOT NULL,
        player_id integer,
        dimension text NOT NULL,
        prompt_version text,
        evaluator_config_hash text,
        input_refs jsonb,
        raw_json jsonb,
        normalized_fields jsonb,
        validator_status text DEFAULT 'valid',
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE wolf.seed_sets (
        seed_set_id text PRIMARY KEY,
        purpose text,
        seeds_json jsonb NOT NULL,
        ruleset_version text DEFAULT 'werewolf_12p_v1',
        created_at timestamptz NOT NULL,
        immutable boolean DEFAULT true
    )
    """,
    """
    CREATE TABLE wolf.evaluation_batches (
        id text PRIMARY KEY,
        comparison_group_id text,
        comparison_type text,
        mode text DEFAULT 'dev',
        model_id text,
        model_config_hash text,
        target_role text,
        target_version_id text,
        role_version_config text,
        game_count integer,
        evaluation_set_id text,
        seed_set_id text,
        max_days integer DEFAULT 20,
        player_count integer DEFAULT 12,
        ruleset_version text DEFAULT 'werewolf_12p_v1',
        rankable boolean DEFAULT false,
        rankable_reason text,
        summary text,
        started_at timestamptz,
        finished_at timestamptz,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE wolf.benchmark_leaderboard (
        id text PRIMARY KEY,
        scope text NOT NULL,
        subject_id text NOT NULL,
        model_id text,
        model_config_hash text,
        target_role text,
        target_version_id text,
        comparison_group_id text,
        evaluation_set_id text,
        seed_set_id text,
        ruleset_version text DEFAULT 'werewolf_12p_v1',
        scoring_version text DEFAULT 'scoring_v1',
        evaluator_config_hash text DEFAULT 'rule_heuristic_v1',
        games_played integer DEFAULT 0,
        valid_game_rate double precision DEFAULT 0.0,
        strength_score double precision DEFAULT 0.0,
        avg_role_score double precision DEFAULT 0.0,
        by_role_category_scores jsonb,
        avg_speech_score double precision DEFAULT 0.0,
        avg_vote_score double precision DEFAULT 0.0,
        avg_skill_score double precision DEFAULT 0.0,
        avg_logic_score double precision DEFAULT 0.0,
        avg_team_score double precision DEFAULT 0.0,
        risk_penalty double precision DEFAULT 0.0,
        fallback_rate double precision DEFAULT 0.0,
        llm_error_rate double precision DEFAULT 0.0,
        policy_adjusted_rate double precision DEFAULT 0.0,
        good_side_win_rate double precision DEFAULT 0.0,
        wolf_side_win_rate double precision DEFAULT 0.0,
        target_side_win_rate double precision DEFAULT 0.0,
        rankable boolean DEFAULT false,
        data_sufficient boolean DEFAULT false,
        summary text,
        updated_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE registry.role_versions (
        id text NOT NULL,
        role text NOT NULL,
        parent_id text,
        source text NOT NULL,
        run_id text,
        skills text NOT NULL,
        notes text,
        status text DEFAULT 'active',
        created_at timestamptz NOT NULL,
        patterns_json jsonb,
        metrics_json jsonb,
        provenance_json jsonb,
        CONSTRAINT pk_role_versions PRIMARY KEY (id, role)
    )
    """,
    """
    CREATE TABLE registry.role_current_baseline (
        role text PRIMARY KEY,
        version_id text NOT NULL,
        updated_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE registry.role_baseline_history (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role text NOT NULL,
        version_id text NOT NULL,
        previous_version_id text,
        reason text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE registry.skill_files (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version_id text NOT NULL,
        file_path text NOT NULL,
        content_hash text NOT NULL,
        content text NOT NULL,
        created_at timestamptz NOT NULL,
        CONSTRAINT uq_skill_files_version_path UNIQUE (version_id, file_path)
    )
    """,
    """
    CREATE TABLE registry.rejected_proposals (
        role text PRIMARY KEY,
        proposals_json jsonb NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.evolution_runs (
        id text PRIMARY KEY,
        role text NOT NULL,
        parent_hash text,
        status text NOT NULL,
        training_games integer DEFAULT 0,
        battle_games integer DEFAULT 0,
        config jsonb,
        candidate_hash text,
        battle_result jsonb,
        runtime_state jsonb,
        errors text,
        started_at timestamptz NOT NULL,
        finished_at timestamptz
    )
    """,
    """
    CREATE TABLE evolution.skill_proposals (
        id text PRIMARY KEY,
        source_version_id text,
        target_version_id text,
        target_file text NOT NULL,
        action_type text NOT NULL,
        content text NOT NULL,
        rationale text,
        confidence double precision,
        risk text,
        expected_metric text,
        expected_direction text,
        evidence jsonb,
        status text DEFAULT 'proposed',
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.experience_candidates (
        game_id text NOT NULL,
        candidate_id text NOT NULL,
        role text,
        faction text,
        candidate_type text,
        topic text,
        sample_source text,
        evidence_decision_ids jsonb,
        scenario text,
        conditions text,
        recommendation text,
        anti_pattern text,
        risk_boundaries text,
        counter_conditions text,
        supporting_evidence text,
        opposing_evidence text,
        confidence text,
        validation_need text,
        misleading_risk text,
        raw_json jsonb NOT NULL,
        created_at timestamptz NOT NULL,
        run_type text DEFAULT 'evolution_training',
        source_run_id text,
        source_game_id text,
        artifact_game_id text,
        learning_eligible boolean DEFAULT true,
        mode text DEFAULT 'formal',
        applicable_phase text,
        applicable_action text,
        llm_rationale text,
        validator_status text,
        CONSTRAINT pk_experience_candidates PRIMARY KEY (game_id, candidate_id)
    )
    """,
    """
    CREATE TABLE evolution.patterns (
        pattern_id text PRIMARY KEY,
        role text NOT NULL,
        situation text NOT NULL,
        recommendation text NOT NULL,
        win_rate_with double precision DEFAULT 0.5,
        win_rate_without double precision DEFAULT 0.5,
        sample_size integer DEFAULT 0,
        confidence double precision DEFAULT 0.1,
        alpha double precision DEFAULT 1.0,
        beta double precision DEFAULT 1.0,
        status text DEFAULT 'candidate',
        source_games jsonb,
        version_id text,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.rejected_proposals (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role text NOT NULL,
        phase text,
        action_type text,
        proposal_json jsonb NOT NULL,
        rejection_reason text,
        rejection_scope text,
        confidence text DEFAULT 'low',
        battle_score_delta double precision,
        battle_win_rate_delta double precision,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.situational_records (
        id text PRIMARY KEY,
        game_id text NOT NULL,
        role text NOT NULL,
        seat integer NOT NULL,
        day integer,
        phase text,
        alive_players text,
        key_events text,
        outcome text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.decision_outcomes (
        decision_id text PRIMARY KEY,
        game_id text NOT NULL,
        player_seat integer NOT NULL,
        role text NOT NULL,
        action_type text NOT NULL,
        day integer NOT NULL,
        phase text NOT NULL,
        quality text,
        reason text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.evolution_rounds (
        round_id text PRIMARY KEY,
        role text NOT NULL,
        branch_id text,
        parent_version_id text,
        generation integer DEFAULT 0,
        status text NOT NULL DEFAULT 'created',
        run_type text DEFAULT 'evolution_training',
        learning_eligible boolean DEFAULT true,
        mode text DEFAULT 'formal',
        training_game_count integer DEFAULT 0,
        config jsonb,
        learning_pipeline_version text,
        started_at timestamptz NOT NULL,
        finished_at timestamptz
    )
    """,
    """
    CREATE TABLE evolution.candidate_packages (
        package_id text PRIMARY KEY,
        round_id text NOT NULL,
        role text NOT NULL,
        candidate_version_id text,
        skill_package_hash text,
        proposal_ids jsonb,
        status text DEFAULT 'pending',
        ab_summary text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.promotion_decisions (
        decision_id text PRIMARY KEY,
        round_id text NOT NULL,
        package_id text NOT NULL,
        role text NOT NULL,
        outcome text NOT NULL,
        reason text,
        metrics jsonb,
        seed_set_id text,
        scoring_version text,
        learning_pipeline_version text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE evolution.ab_comparison_groups (
        group_id text PRIMARY KEY,
        round_id text NOT NULL,
        role text NOT NULL,
        baseline_run_id text,
        candidate_run_id text,
        game_count integer DEFAULT 0,
        summary text,
        created_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE wolf.ui_background_tasks (
        entity_id text PRIMARY KEY,
        entity_kind text NOT NULL,
        status text,
        payload jsonb NOT NULL,
        updated_at timestamptz NOT NULL
    )
    """,
    """
    CREATE TABLE wolf.ui_task_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        entity_id text NOT NULL,
        entity_kind text,
        event text,
        status text,
        payload jsonb NOT NULL,
        created_at timestamptz NOT NULL
    )
    """,
)


INDEX_STATEMENTS = (
    "CREATE INDEX idx_decisions_game ON wolf.decisions(game_id)",
    "CREATE INDEX idx_decisions_role ON wolf.decisions(role)",
    "CREATE INDEX idx_decisions_version ON wolf.decisions(version_id)",
    "CREATE INDEX idx_decisions_action ON wolf.decisions(action_type)",
    "CREATE INDEX idx_decisions_created ON wolf.decisions(created_at)",
    "CREATE INDEX idx_players_game ON wolf.players(game_id)",
    "CREATE INDEX idx_players_role ON wolf.players(role)",
    "CREATE INDEX idx_leaderboard_role ON wolf.leaderboard(role)",
    "CREATE INDEX idx_leaderboard_version ON wolf.leaderboard(version_id)",
    "CREATE INDEX idx_ge_game ON wolf.game_events(game_id)",
    "CREATE INDEX idx_ge_type ON wolf.game_events(event_type)",
    "CREATE INDEX idx_ge_day ON wolf.game_events(game_id, day)",
    "CREATE INDEX idx_eval_game ON wolf.evaluations(game_id)",
    "CREATE INDEX idx_eval_role ON wolf.evaluations(role)",
    "CREATE INDEX idx_dr_game ON wolf.decision_reviews(game_id)",
    "CREATE INDEX idx_dr_decision ON wolf.decision_reviews(decision_id)",
    "CREATE INDEX idx_cf_game ON wolf.counterfactuals(game_id)",
    "CREATE INDEX idx_cf_decision ON wolf.counterfactuals(decision_id)",
    "CREATE INDEX idx_judgment_game ON wolf.llm_judgments(game_id)",
    "CREATE INDEX idx_judgment_player ON wolf.llm_judgments(player_id)",
    "CREATE INDEX idx_judgment_dimension ON wolf.llm_judgments(dimension)",
    "CREATE INDEX idx_games_run_type ON wolf.games(run_type)",
    "CREATE INDEX idx_games_learning ON wolf.games(learning_eligible)",
    "CREATE INDEX idx_games_leaderboard ON wolf.games(leaderboard_scope)",
    "CREATE INDEX idx_eval_batches_group ON wolf.evaluation_batches(comparison_group_id)",
    "CREATE INDEX idx_eval_batches_type ON wolf.evaluation_batches(comparison_type)",
    "CREATE INDEX idx_bench_scope ON wolf.benchmark_leaderboard(scope)",
    "CREATE INDEX idx_bench_subject ON wolf.benchmark_leaderboard(subject_id)",
    "CREATE INDEX idx_bench_group ON wolf.benchmark_leaderboard(comparison_group_id)",
    "CREATE INDEX idx_role_versions_role ON registry.role_versions(role)",
    "CREATE INDEX idx_role_versions_status ON registry.role_versions(status)",
    "CREATE INDEX idx_skill_files_version ON registry.skill_files(version_id)",
    "CREATE INDEX idx_evolution_runs_role ON evolution.evolution_runs(role)",
    "CREATE INDEX idx_ui_background_tasks_kind ON wolf.ui_background_tasks(entity_kind)",
    "CREATE INDEX idx_ui_task_events_entity_id ON wolf.ui_task_events(entity_id, id)",
    "CREATE INDEX idx_skill_proposals_source ON evolution.skill_proposals(source_version_id)",
    "CREATE INDEX idx_exp_game ON evolution.experience_candidates(game_id)",
    "CREATE INDEX idx_exp_role ON evolution.experience_candidates(role)",
    "CREATE INDEX idx_exp_type ON evolution.experience_candidates(candidate_type)",
    "CREATE INDEX idx_exp_created ON evolution.experience_candidates(created_at)",
    "CREATE INDEX idx_exp_run_type ON evolution.experience_candidates(run_type)",
    "CREATE INDEX idx_exp_learning ON evolution.experience_candidates(learning_eligible)",
    "CREATE INDEX idx_patterns_role ON evolution.patterns(role)",
    "CREATE INDEX idx_patterns_status ON evolution.patterns(status)",
    "CREATE INDEX idx_rejected_role ON evolution.rejected_proposals(role)",
    "CREATE INDEX idx_situational_game ON evolution.situational_records(game_id)",
    "CREATE INDEX idx_situational_role ON evolution.situational_records(role)",
    "CREATE INDEX idx_outcomes_game ON evolution.decision_outcomes(game_id)",
    "CREATE INDEX idx_outcomes_role ON evolution.decision_outcomes(role)",
    "CREATE INDEX idx_outcomes_decision ON evolution.decision_outcomes(decision_id)",
    "CREATE INDEX idx_evo_rounds_role ON evolution.evolution_rounds(role)",
    "CREATE INDEX idx_evo_rounds_status ON evolution.evolution_rounds(status)",
    "CREATE INDEX idx_candidate_pkg_round ON evolution.candidate_packages(round_id)",
    "CREATE INDEX idx_promo_round ON evolution.promotion_decisions(round_id)",
    "CREATE INDEX idx_ab_group_round ON evolution.ab_comparison_groups(round_id)",
)


def upgrade() -> None:
    for statement in (*SCHEMA_STATEMENTS, *TABLE_STATEMENTS, *INDEX_STATEMENTS):
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS evolution CASCADE")
    op.execute("DROP SCHEMA IF EXISTS registry CASCADE")
    op.execute("DROP SCHEMA IF EXISTS wolf CASCADE")
